# Site settings
title: Wesley Heung
email: wesley@heungs.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-paginator-links" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username: Shadowen

# GitHub defaults
highlighter: pygments

# Build settings
markdown: kramdown
markdown_ext: "md"
input: GFM

paginate: 2

# Collections
collections:
  galleryA:
    output: true
    permalink: /galleryA/:path/
  galleryB:
    output: true
    permalink: /galleryB/:path/

# default settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      author: ME
      layout: post
      class: article
  - scope:
      path: "" # an empty string here means all files in the project
      type: not_posts
    values:
      author: ME
      layout: post
      class: article

# GitHub overrides
safe: true
lsi: false